//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Capitalflow
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string flowType { get; set; }
        public decimal money { get; set; }
        public string otherUser { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
