//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Capitalflow
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string flowType { get; set; }
        public decimal money { get; set; }
        public string otherUser { get; set; }
        public System.DateTime created { get; set; }
        public string describe { get; set; }
        public decimal curMoney { get; set; }
        public bool isIncome { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
