//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_grade()
        {
            this.tb_UserAccount = new HashSet<tb_UserAccount>();
        }
    
        public int id { get; set; }
        public string grade { get; set; }
        public decimal Rewardpercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UserAccount> tb_UserAccount { get; set; }
    }
}
