//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Notice
    {
        public int nid { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public bool isShow { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
