//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Notice
    {
        public int nid { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string creator { get; set; }
        public System.DateTime created { get; set; }
        public bool isShow { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
