//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_params
    {
        public System.Guid id { get; set; }
        public string paramkey { get; set; }
        public string paramStrValue { get; set; }
        public Nullable<int> paramIntValue { get; set; }
        public Nullable<decimal> paramFloatValue { get; set; }
        public string describe { get; set; }
    }
}
