//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserAccount
    {
        public string Id { get; set; }
        public decimal money { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modify { get; set; }
        public string paypwd { get; set; }
        public string moneybag { get; set; }
        public int MinerType { get; set; }
        public System.DateTime endTime { get; set; }
        public string Referee { get; set; }
        public int MyGrade { get; set; }
        public int RecommendA0 { get; set; }
        public int RecommendA1 { get; set; }
        public int RecommendA2 { get; set; }
        public int RecommendA3 { get; set; }
        public int RecommendB1 { get; set; }
        public int RecommendB2 { get; set; }
        public int RecommendB3 { get; set; }
        public int RecommendC1 { get; set; }
        public int RecommendC2 { get; set; }
        public int RecommendC3 { get; set; }
        public int RecommendS { get; set; }
        public decimal directAward { get; set; }
        public decimal indirectAward { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tb_grade tb_grade { get; set; }
    }
}
