//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserAccount
    {
        public string Id { get; set; }
        public decimal money { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modify { get; set; }
        public string paypwd { get; set; }
        public string moneybag { get; set; }
        public int MinerType { get; set; }
        public System.DateTime endTime { get; set; }
        public string Referee { get; set; }
        public int MyGrade { get; set; }
        public int RecommendA0 { get; set; }
        public int RecommendA1 { get; set; }
        public int RecommendA2 { get; set; }
        public int RecommendA3 { get; set; }
        public int RecommendB1 { get; set; }
        public int RecommendB2 { get; set; }
        public int RecommendB3 { get; set; }
        public int RecommendC1 { get; set; }
        public int RecommendC2 { get; set; }
        public int RecommendC3 { get; set; }
        public int RecommendS { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tb_grade tb_grade { get; set; }
    }
}
