//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tb_grade> tb_grade { get; set; }
        public virtual DbSet<tb_MinerType> tb_MinerType { get; set; }
        public virtual DbSet<tb_params> tb_params { get; set; }
        public virtual DbSet<tb_UserAccount> tb_UserAccount { get; set; }
        public virtual DbSet<tb_Capitalflow> tb_Capitalflow { get; set; }
        public virtual DbSet<tb_coefficient> tb_coefficient { get; set; }
        public virtual DbSet<tb_Notice> tb_Notice { get; set; }
        public virtual DbSet<tb_reward_coefficient> tb_reward_coefficient { get; set; }
    }
}
