//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tb_MinerType> tb_MinerType { get; set; }
        public virtual DbSet<tb_Notice> tb_Notice { get; set; }
        public virtual DbSet<tb_params> tb_params { get; set; }
        public virtual DbSet<tb_grade> tb_grade { get; set; }
        public virtual DbSet<tb_UserAccount> tb_UserAccount { get; set; }
        public virtual DbSet<tb_Capitalflow> tb_Capitalflow { get; set; }
        public virtual DbSet<tb_eventlog> tb_eventlog { get; set; }
    }
}
